Repository CESARBR/knot-cloud, pull requests merged in 2020-07, with the labels that each got.

#41 Bump version to v3.0.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: priority: medium, release

#44 add jaeger dependency on authn
  stacks/core/base/base.yml
Labels: enhancement, priority: low

#45 docs: Add secret creation instruction
  stacks/core/README.md
Labels: enhancement, priority: medium
